configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - "setupmobans/templates"
  - ".moban.d"
  configuration: pyexcel-ezodf.yml
targets:
  - README.rst: README.rst
  - setup.py: setup.py
